// Implementation file for parser generated by fsyacc
module RegexPar
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open Microsoft.FSharp.Text.Lexing
open Microsoft.FSharp.Text.Parsing.ParseHelpers
# 1 "RegexPar.fsy"

  (* File RegEx/RegexPar.fsy
     Parser specification for the simple regular expression language.
   *)

  open Absyn

# 14 "RegexPar.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | LPAR
  | RPAR
  | OR
  | EPS
  | TIMES
  | CHAR of (char)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_LPAR
    | TOKEN_RPAR
    | TOKEN_OR
    | TOKEN_EPS
    | TOKEN_TIMES
    | TOKEN_CHAR
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startMain
    | NONTERM_Main
    | NONTERM_Re

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | LPAR  -> 1 
  | RPAR  -> 2 
  | OR  -> 3 
  | EPS  -> 4 
  | TIMES  -> 5 
  | CHAR _ -> 6 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_LPAR 
  | 2 -> TOKEN_RPAR 
  | 3 -> TOKEN_OR 
  | 4 -> TOKEN_EPS 
  | 5 -> TOKEN_TIMES 
  | 6 -> TOKEN_CHAR 
  | 9 -> TOKEN_end_of_input
  | 7 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startMain 
    | 1 -> NONTERM_Main 
    | 2 -> NONTERM_Re 
    | 3 -> NONTERM_Re 
    | 4 -> NONTERM_Re 
    | 5 -> NONTERM_Re 
    | 6 -> NONTERM_Re 
    | 7 -> NONTERM_Re 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 9 
let _fsyacc_tagOfErrorTerminal = 7

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | LPAR  -> "LPAR" 
  | RPAR  -> "RPAR" 
  | OR  -> "OR" 
  | EPS  -> "EPS" 
  | TIMES  -> "TIMES" 
  | CHAR _ -> "CHAR" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | LPAR  -> (null : System.Object) 
  | RPAR  -> (null : System.Object) 
  | OR  -> (null : System.Object) 
  | EPS  -> (null : System.Object) 
  | TIMES  -> (null : System.Object) 
  | CHAR _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 7us; 65535us; 0us; 2us; 2us; 9us; 5us; 6us; 6us; 9us; 8us; 9us; 9us; 9us; 11us; 8us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 4us; 1us; 4us; 5us; 6us; 1us; 1us; 1us; 2us; 1us; 3us; 4us; 3us; 4us; 5us; 6us; 1us; 3us; 4us; 4us; 5us; 5us; 6us; 4us; 4us; 5us; 6us; 6us; 1us; 4us; 1us; 5us; 1us; 7us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 9us; 11us; 13us; 15us; 20us; 22us; 27us; 32us; 34us; 36us; |]
let _fsyacc_action_rows = 13
let _fsyacc_actionTableElements = [|3us; 32768us; 1us; 5us; 4us; 12us; 6us; 4us; 0us; 49152us; 6us; 32768us; 0us; 3us; 1us; 5us; 3us; 11us; 4us; 12us; 5us; 10us; 6us; 4us; 0us; 16385us; 0us; 16386us; 3us; 32768us; 1us; 5us; 4us; 12us; 6us; 4us; 6us; 32768us; 1us; 5us; 2us; 7us; 3us; 11us; 4us; 12us; 5us; 10us; 6us; 4us; 0us; 16387us; 4us; 16389us; 1us; 5us; 4us; 12us; 5us; 10us; 6us; 4us; 4us; 16390us; 1us; 5us; 4us; 12us; 5us; 10us; 6us; 4us; 0us; 16388us; 3us; 32768us; 1us; 5us; 4us; 12us; 6us; 4us; 0us; 16391us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 4us; 5us; 12us; 13us; 14us; 18us; 25us; 26us; 31us; 36us; 37us; 41us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 2us; 1us; 3us; 2us; 3us; 2us; 1us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 2us; 2us; 2us; 2us; 2us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 65535us; 16385us; 16386us; 65535us; 65535us; 16387us; 65535us; 65535us; 16388us; 65535us; 16391us; |]
let _fsyacc_reductions ()  =    [| 
# 114 "RegexPar.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : Absyn.re)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (Microsoft.FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startMain));
# 123 "RegexPar.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'Re)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 26 "RegexPar.fsy"
                                                               _1                
                   )
# 26 "RegexPar.fsy"
                 : Absyn.re));
# 134 "RegexPar.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : char)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 30 "RegexPar.fsy"
                                                               Char _1           
                   )
# 30 "RegexPar.fsy"
                 : 'Re));
# 145 "RegexPar.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'Re)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 31 "RegexPar.fsy"
                                                               _2                
                   )
# 31 "RegexPar.fsy"
                 : 'Re));
# 156 "RegexPar.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'Re)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 32 "RegexPar.fsy"
                                                               Star _1           
                   )
# 32 "RegexPar.fsy"
                 : 'Re));
# 167 "RegexPar.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'Re)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'Re)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 33 "RegexPar.fsy"
                                                               Choice(_1, _3)    
                   )
# 33 "RegexPar.fsy"
                 : 'Re));
# 179 "RegexPar.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'Re)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'Re)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 34 "RegexPar.fsy"
                                                               Seq(_1, _2)       
                   )
# 34 "RegexPar.fsy"
                 : 'Re));
# 191 "RegexPar.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 35 "RegexPar.fsy"
                                                               Eps               
                   )
# 35 "RegexPar.fsy"
                 : 'Re));
|]
# 202 "RegexPar.fs"
let tables () : Microsoft.FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:Microsoft.FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 10;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let Main lexer lexbuf : Absyn.re =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
